### ISSUE TITLE
View tree not inspectable with ember 1.13

### ISSUE THREAD

**Issue by formigarafa** [tricknotes/ember-handlebars-template#13]
There is a issue in ember inspector causing me some headaches.
emberjs/ember-inspector#419

When I upgrade to ember 1.13 the view tree of the ember inspector does not work in a few of my projects, others do.

I could narrow down the problem to the lack of a meta information on compiled templates, namely `moduleName`.

I noticed the projects using ember-handlebars-template gems does not produce them.

As far as I could understand this would be resolved passing in the template name as an extra argument in the compilation process, but I couldn't figure out how to get this done, yet.

Probably in `lib/ember/handlebar/helper.rb`, This is the part of the code where ruby meets js, and I am not so sure about witch action can I take to fix it.

I would really appreciate if anyone could help me with that.

**Comment by tricknotes** [comment]
Fixed by https://github.com/tricknotes/ember-handlebars-template/pull/14
