### ISSUE TITLE
`precompile_handlebars` given 1 argument, should be 2.

### ISSUE THREAD

**Issue by kaukas** [tricknotes/ember-handlebars-template#18]
Hello.

I am trying to use `ember-handlebars-template` to precompile Ember as well as bare Handlebars templates. The Ember templates work fine. For standalone Handlebars templates I am getting:

```
ActionView::Template::Error: wrong number of arguments (1 for 2)
    .../ruby/2.2.0/gems/ember-handlebars-template-0.6.0/lib/ember/handlebars/template.rb:101:in `precompile_handlebars'
    .../ruby/2.2.0/gems/ember-handlebars-template-0.6.0/lib/ember/handlebars/template.rb:75:in `call'
    .../ruby/2.2.0/gems/ember-handlebars-template-0.6.0/lib/ember/handlebars/template.rb:33:in `call'
    ...
```

Apparently [`precompile_handlebars`](https://github.com/tricknotes/ember-handlebars-template/blob/master/lib/ember/handlebars/template.rb#L101) takes two arguments `(template, input)` while [a call in `call`](https://github.com/tricknotes/ember-handlebars-template/blob/master/lib/ember/handlebars/template.rb#L75) supplies only one. Adding `input` as a second argument solves the issue.

I could submit a fix but do not know how to write a test. Could you please help?

Thank you!

**Comment by kaukas** [comment]
Turns out the code path for "raw" templates is not tested at all.

I wrote a test. In order to make it pass I had to add a `handlebars-source` development dependency (I appreciate you may not want to have it as a standard dependency). The test passes but now another one fails:

```
TestEmberHandlebarsTemplate#test_should_respond_with_handlebars_detection [/Users/linas/code/ember-handlebars-template/test/test_ember_handlebars_template.rb:172]:
This optional feature should be `false` by default..
Expected: true
  Actual: false
```

What should I do about it?

**Comment by tricknotes** [comment]
Thanks for your reporting @kaukas
I'm truly sorry for untested feature.

I'm going to solve this issue.
Could you submit your test code as PR?
It is OK that has failing test!

**Comment by tricknotes** [comment]
Fixed by https://github.com/tricknotes/ember-handlebars-template/pull/19
