### ISSUE TITLE
Raw templates should live under a different namespace

### ISSUE THREAD

**Issue by kaukas** [tricknotes/ember-handlebars-template#20]
`Ember.TEMPLATES` make sense for Ember Handlebars templates but not for raw ones. I've seen that `JST` is used [by convention](http://underscorejs.org/#template). But you might want to have it configurable.

Judging by the fact that raw template compilation did not work at all I suspect not many were using it. Which means it is a good time to introduce a breaking change – a `JST` as a default and a configurable option in case you need it. The change is [in my repository](https://github.com/kaukas/ember-handlebars-template/commit/b8cc2e75b9d5a45159d46540142ae50eceeec74d). I can create a PR when you merge #18.

Thank you!

**Comment by tricknotes** [comment]
It seems the commit to fix this issue is landed on #19 .
I thinks this is good for one PR :+1: 

Thanks @kaukas !

**Comment by tricknotes** [comment]
Fixed by https://github.com/tricknotes/ember-handlebars-template/pull/19
