### ISSUE TITLE
Define cache_key on Ember::Handlebars::Template

### ISSUE THREAD

**Issue by afn** [tricknotes/ember-handlebars-template#8]
We recently ran into an issue having to do with the Sprockets cache not being invalidated when changing the `templates_root` configuration.  See script below for an example of how to reproduce the bug.

The fix is to define the `cache_key` method on Ember::Handlebars::Template.  This feature was added to Sprockets in https://github.com/sstephenson/sprockets/pull/672, and allows processors to define dependencies on things like version numbers and configuration variables.  Any relevant config, including `templates_root`, should be defined for `Ember::Handlebars::Template#cache_key`.

To reproduce:

``` bash
rails new test1
cd test1
echo "gem 'ember-handlebars-template'" >>Gemfile
bundle
echo "Sprockets.register_engine '.hbs', Ember::Handlebars::Template" >config/initializers/sprockets.rb
mkdir app/assets/javascripts/foo
mkdir app/assets/javascripts/foo/templates
echo '//= require_tree ./templates' >app/assets/javascripts/foo/application.js
echo 'foo' >app/assets/javascripts/foo/templates/template.hbs
rake assets:precompile

head -n1 /Users/afn/test1/public/assets/foo/application-*.js
# => Ember.TEMPLATES["foo/template"] = Ember.HTMLBars.template((function() {

echo 'Ember::Handlebars::Template.configure {|config| config.templates_root = %w(foo/templates)}' >config/initializers/handlebars.rb
rake assets:precompile
head -n1 /Users/afn/test1/public/assets/foo/application-*.js
# => Ember.TEMPLATES["foo/template"] = Ember.HTMLBars.template((function() {
# ^^^ That's wrong.  rake assets:precompile should have updated the contents of the file.

rake assets:clobber
rake assets:precompile
head -n1 /Users/afn/test1/public/assets/foo/application-*.js
# => Ember.TEMPLATES["template"] = Ember.HTMLBars.template((function() {
# ^^^ That's the right value, which I would have expected earlier, without having to explicitly clear the cache
```

Thanks!
Tony

**Comment by tricknotes** [comment]
Oops, this is a regression introduced by https://github.com/tricknotes/ember-handlebars-template/pull/6

**Comment by tricknotes** [comment]
This issue was fixed by https://github.com/tricknotes/ember-handlebars-template/pull/10 and using Sprockets 3.3.
